item {
  id: 1
  name: 'Seribu'
}

item {
  id: 2
  name: 'Duaribu'
}

item {
  id: 3
  name: 'Limaribu'
}

item {
  id: 4
  name: 'Sepuluhribu'
}

item {
  id: 5
  name: 'Duapuluhribu'
}

item {
  id: 6
  name: 'Limapuluhribu'
}

item {
  id: 7
  name: 'Seratusribu'
}

